### ISSUE TITLE
PS 8.0.0: cURL error 6: Could not resolve host: v1 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for v1/customers/

### ISSUE THREAD

**Issue by urbanovich** [PrestaShopCorp/module-lib-billing#15]
Hello!

I'm using the library on PS 8.0.0, and in time execution:

```php
// Load service for PsBilling
$billingService = $this->getService('ps_billings.service');

// Retrieve the customer
$customer = $billingService->getCurrentCustomer();
```

I see the error: ``` cURL error 6: Could not resolve host: v1 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for v1/customers/```

The library works with PS 8.0.0 or need to set up any dependencies else? I understand that the lib should understand which domain uses for connect to billing service. The extension works with PS 1.7.8.8 as need.

**Comment by jmcollin** [comment]
Hello @urbanovich!

Thank you for your report

Which version of `module-lib-billing` have you ?
I think that version v1.x is currently not compatible with v8.x of PrestaShop, I just made a small PR to fix it.

___
Also If you have 2 modules `ModuleA` and `ModuleB` installed in V8

If `ModuleA` uses the lib in v1.x and  `ModuleB` in v2.x, PrestaShop, unfortunately, does not make the difference between the namespace and will take the lib from module `ModuleA`.

Currently, v1.x doesn't use this lib `prestashop/module-lib-guzzle-adapter` that allowing backward compatibility with Guzzle 5 (PrestaShop 1.7) & Guzzle 7 (PrestaShop v8)

That's why you got this CURL error
